### PR TITLE
iOS-OTA-Downgrader Guide

### PR DESCRIPTION
**Pull request by dabezt31**
make a guide for iOS OTA Downgrader,

### CODE REVIEW

**Review by hopolapopola — APPROVED** [review]
to quote an awful person, LGTM!

but seriously, it seems fine since you basically just copy pasted the github readme's key bits

**Comment by Tanbeer191** [comment]
`When asked if you want to jailbreak the firmware you're restoring to refuse, as that tends to be unreliable`

Reword this part a bit, seems a bit tacky

Enter “[2] No” when prompted if you want to jailbreak the target version, because this tends to be unreliable.

Also, source?

**Comment by hopolapopola** [comment]
> `Enter “[2] No” when prompted if you want to jailbreak the target version, because this tends to be unreliable.`
> 
> Also, source?
it's etason that's sometimes unreliable for some devices, though 6.1.3 doesn't have this same issue afaik. also would check the issues on ios-ota-downgrader because i remember there being discussion of using daibutsu instead of etason in some cases which is more reliable but also can break coolbooter, which is probably what a lot of people use for their ios 6 stuff

**Comment by dabezt31** [comment]
> `When asked if you want to jailbreak the firmware you're restoring to refuse, as that tends to be unreliable`
> 
> Reword this part a bit, seems a bit tacky
> 
> `Select “[2] No” when prompted if you want to jailbreak the target version, because this tends to be unreliable.`
> 
> Also, source?

Doja Cat

**Comment by Tanbeer191** [comment]
> > `Enter “[2] No” when prompted if you want to jailbreak the target version, because this tends to be unreliable.`
> > Also, source?
> 
> it's etason that's sometimes unreliable for some devices, though 6.1.3 doesn't have this same issue afaik. also would check the issues on ios-ota-downgrader because i remember there being discussion of using daibutsu instead of etason in some cases which is more reliable but also can break coolbooter, which is probably what a lot of people use for their ios 6 stuff

The only problem I can find is that Cydia doesn’t appear on the home screen at first boot, you have to enter cydia:// in Safari and then install a seperate package for that. Unless I’m just being blind?

**Review by shulkk — APPROVED** [review]

**Comment by dabezt31** [comment]
:fr:

**Pull request closed without merging**
