### PR TITLE
Chimera works on ios 12.5.7

### PR DESCRIPTION
**Pull request by rastiqdev**
Change FAQ info saying latest version compatible with A7-A8 is ios 12.5.6 to 12.6.7

### CODE REVIEW

**Review by TheMasterOfMike — CHANGES_REQUESTED** [review]
Odysseyra1n is still supported on 12.5.7, and should be listed there.

**Comment by rastiqdev** [comment]
Odysseyra1n works but libhooker doesn't. (that's in fact why it says it doesn't work on appledb)

**Comment by TheMasterOfMike** [comment]
> Odysseyra1n works but libhooker doesn't. (that's in fact why it says it doesn't work on appledb)

no? Just downgrade libhooker (really should add steps to this soon, this impacts 12/13 with 1.6.9-1 by the way)

probably wasn’t added to AppleDB due to forgetfulness on our end

**Comment by rastiqdev** [comment]
Ok, modified the file.

**Pull request closed without merging**
