### PR TITLE
Added Blobs Section in FAQ page

### PR DESCRIPTION
**Pull request by shulkk**
i noticed that there was no explanation in the faq about blobs, so i added one.

### CODE REVIEW

**Comment by hopolapopola** [comment]
it's a little overly simplified imo. it would be perfectly adequate for 32bit devices however 64bit (i.e. modern) devices have SEP to deal with as well, which is something that should definitely mentioned i think

**Comment by asdfugil** [comment]
Also baseband compatibility for cellular capable devices.

As well as FDR compatibility which is an issue for iOS/iPadOS 14.2 restores

**Comment by nyuszika7h** [comment]
The part about onboard blobs is misleading as well. You can only save onboard blobs for the version you're *currently* on, not any arbitrary unsigned version.

**Comment by shulkk** [comment]
would it be better to explain SEP/baseband compatibility on a new section, or the same one, or on another page?

**Pull request closed without merging**
