### PR TITLE
Remove instructions on adding chariz on futurerestore pages 

### PR DESCRIPTION
**Pull request by Serena-io**
and remove copy-pasted instructions on how to set nonce in futurerestore-help, instead, redirect the users to the original fr page to see how to set nonce

### CODE REVIEW

**Comment by emiyl** [comment]
thank you!

**Comment by Serena-io** [comment]
@emiyl thanks for merging but.. I originally wrote this page LOL https://github.com/cfw-guide/ios.cfw.guide/pull/62

**Comment by emiyl** [comment]
i'm confused what you mean by that, sorry

if you're referring to the extra_credits thing, the site will automatically add your name at the bottom now that you've commited to the page since the theme changed

**Comment by Serena-io** [comment]
Ah, got it!

**Pull request merged**
