### PR TITLE
Updated tvOS profile

### PR DESCRIPTION
**Pull request by c22dev**
This update tvOS 16 profile to tvOS 17 profile. It should expire less sooner than tvOS16.

All credit goes to nebula !

### CODE REVIEW

**Comment by TheMasterOfMike** [comment]
Looks good, just wanting to note before I merge this that you don’t need to add yourself to extra contributors if you commit something yourself

extra contributors are _only_ for people who contributed something, but didn’t commit to the guide

**Comment by c22dev** [comment]
Alright, you can remove me from it.

**Comment by TheMasterOfMike** [comment]
Thanks

**Comment by gamer191** [comment]
Thanks, the tvOS 17 profile doesn’t self destruct until 2025, so I can now use it for an extra year 🎉

Unfortunately, it’s certificate expires tomorrow, so we have a slight problem

**Comment by TheMasterOfMike** [comment]
> Thanks, the tvOS 17 profile doesn’t self destruct until 2025, so I can now use it for an extra year 🎉
> 
> Unfortunately, it’s certificate expires tomorrow, so we have a slight problem

just set your date back to today or yesterday

**Comment by gamer191** [comment]
> just set your date back to today or yesterday

Do you want me to write a PR adding that to the guide?

**Pull request merged**
