### PR TITLE
Add Odysseyra1n for A9X guide

### PR DESCRIPTION
**Pull request by TheMasterOfMike**
Context: So, on A9X devices if you're on 14.5+ you're kinda screwed because:
- checkra1n 0.12.2 doesn't support 14.5+
- checkra1n 0.12.3+ have issues in relation to "detected corrupted kerninfo" on A9X devices

The way to work around this is to use a custom pongoOS and checkra1n CLI with checkra1n 0.12.4 ((or also 0.12.3 I guess but why), but up until this PR, we haven't attempted to add this due to the fact that adding it into the current setup of the guide would've been a pain in the ass.

What is being done now is to simply make a whole separate page for A9X, since the addition of this into the current page would've been a bigger pain than it was worth.

(Note: You cannot use this with Odysseyn1x due to Odysseyn1x not having internet connectivity and also not having an easy/reasonable way to add the custom pongoOS necessary to allow this to work, this is also made clear in the relevant pages)

### CODE REVIEW

**Comment by asdfugil** [comment]
You can mount a filesystem from odysseyn1x shell and tell checkra1n from the shell to use a copy of the shell from the said mounted filesystem.

**Comment by asdfugil** [comment]
Here's two custom odysseyn1x ISOs that are tested to work. The release is somewhat polished.

https://github.com/asdfugil/checkn1x_a9x_kerninfo_pongoOS/releases/tag/14.5-a9x-1

**Comment by asdfugil** [comment]
the actual requirement for the usb drive is about 200 MB but it looks good to me.

**Comment by TheMasterOfMike** [comment]
> the actual requirement for the usb drive is about 200 MB but it looks good to me.

True but I mean if you only have a 200MB USB drive then that's a huge edge case which should almost never be true.

**Comment by asdfugil** [comment]
256 MB :)

**Pull request merged**
